# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63oder.proto\x12\nsdlc.coder\x1a\x0c\x63ommon.proto\"\xa0\x01\n\x0b\x43oderOutput\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.sdlc.common.Status\x12\x12\n\nconfidence\x18\x03 \x01(\x05\x12\x32\n\x0eimplementation\x18\x04 \x01(\x0b\x32\x1a.sdlc.coder.Implementation\x12\x15\n\rmarkdown_body\x18\x05 \x01(\t\"\xe4\x01\n\x0eImplementation\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\'\n\x07\x63hanges\x18\x03 \x03(\x0b\x32\x16.sdlc.coder.CodeChange\x12+\n\tnew_files\x18\x04 \x03(\x0b\x32\x18.sdlc.coder.FileCreation\x12-\n\x05notes\x18\x05 \x03(\x0b\x32\x1e.sdlc.coder.ImplementationNote\x12\x14\n\x0crequest_peer\x18\x06 \x01(\x08\x12\x15\n\rpeer_question\x18\x07 \x01(\t\"\xb6\x01\n\nCodeChange\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.sdlc.coder.ChangeType\x12\x14\n\x0csearch_block\x18\x03 \x01(\t\x12\x15\n\rreplace_block\x18\x04 \x01(\t\x12\x1d\n\x10\x61pproximate_line\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x06reason\x18\x06 \x01(\tB\x13\n\x11_approximate_line\"Z\n\x0c\x46ileCreation\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07purpose\x18\x03 \x01(\t\x12\x15\n\rtemplate_used\x18\x04 \x01(\t\"0\n\x12ImplementationNote\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04note\x18\x02 \x01(\t*M\n\nChangeType\x12\x1b\n\x17\x43HANGE_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06MODIFY\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\n\n\x06RENAME\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGETYPE']._serialized_start=762
  _globals['_CHANGETYPE']._serialized_end=839
  _globals['_CODEROUTPUT']._serialized_start=42
  _globals['_CODEROUTPUT']._serialized_end=202
  _globals['_IMPLEMENTATION']._serialized_start=205
  _globals['_IMPLEMENTATION']._serialized_end=433
  _globals['_CODECHANGE']._serialized_start=436
  _globals['_CODECHANGE']._serialized_end=618
  _globals['_FILECREATION']._serialized_start=620
  _globals['_FILECREATION']._serialized_end=710
  _globals['_IMPLEMENTATIONNOTE']._serialized_start=712
  _globals['_IMPLEMENTATIONNOTE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
