# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0bsdlc.common\"~\n\rFileReference\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x17\n\nstart_line\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08\x65nd_line\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\tB\r\n\x0b_start_lineB\x0b\n\t_end_line\"}\n\tComponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12)\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x1a.sdlc.common.FileReference\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x05 \x03(\t\"d\n\x04Risk\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\'\n\x08severity\x18\x03 \x01(\x0e\x32\x15.sdlc.common.Severity\x12\x12\n\nmitigation\x18\x04 \x01(\t\"]\n\rTechnicalDebt\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\'\n\x08severity\x18\x02 \x01(\x0e\x32\x15.sdlc.common.Severity\x12\x0e\n\x06reason\x18\x03 \x01(\t*\x89\x01\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x43OMPLETE\x10\x01\x12\x0e\n\nINCOMPLETE\x10\x02\x12\x0f\n\x0bIN_PROGRESS\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\x10\n\x0cNEEDS_REVIEW\x10\x05\x12\x0c\n\x08\x41PPROVED\x10\x06\x12\x0c\n\x08REJECTED\x10\x07*Q\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=482
  _globals['_STATUS']._serialized_end=619
  _globals['_SEVERITY']._serialized_start=621
  _globals['_SEVERITY']._serialized_end=702
  _globals['_FILEREFERENCE']._serialized_start=29
  _globals['_FILEREFERENCE']._serialized_end=155
  _globals['_COMPONENT']._serialized_start=157
  _globals['_COMPONENT']._serialized_end=282
  _globals['_RISK']._serialized_start=284
  _globals['_RISK']._serialized_end=384
  _globals['_TECHNICALDEBT']._serialized_start=386
  _globals['_TECHNICALDEBT']._serialized_end=479
# @@protoc_insertion_point(module_scope)
