# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: github_scanner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'github_scanner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14github_scanner.proto\x12\x13sdlc.github_scanner\x1a\x0c\x63ommon.proto\"\xa3\x01\n\x13GitHubScannerOutput\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.sdlc.common.Status\x12\x12\n\nconfidence\x18\x03 \x01(\x05\x12-\n\x05issue\x18\x04 \x01(\x0b\x32\x1e.sdlc.github_scanner.IssueData\x12\x15\n\rmarkdown_body\x18\x05 \x01(\t\"\xdb\x01\n\tIssueData\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0e\n\x06labels\x18\x05 \x03(\t\x12\x12\n\nissue_type\x18\x06 \x01(\t\x12\x37\n\ncomponents\x18\x07 \x03(\x0b\x32#.sdlc.github_scanner.IssueComponent\x12\x37\n\x0crequirements\x18\x08 \x01(\x0b\x32!.sdlc.github_scanner.Requirements\"\x9b\x01\n\x0eIssueComponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0esub_components\x18\x03 \x03(\t\x12\x18\n\x10\x62\x61\x63kend_required\x18\x04 \x01(\x08\x12\x19\n\x11\x66rontend_required\x18\x05 \x01(\x08\x12\x19\n\x11\x64\x61tabase_required\x18\x06 \x01(\x08\"\x83\x01\n\x0cRequirements\x12\x12\n\nfunctional\x18\x01 \x03(\t\x12\x16\n\x0enon_functional\x18\x02 \x03(\t\x12\x1b\n\x13\x61\x63\x63\x65ptance_criteria\x18\x03 \x03(\t\x12\x14\n\x0cuser_stories\x18\x04 \x03(\t\x12\x14\n\x0c\x64\x61ta_sources\x18\x05 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'github_scanner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GITHUBSCANNEROUTPUT']._serialized_start=60
  _globals['_GITHUBSCANNEROUTPUT']._serialized_end=223
  _globals['_ISSUEDATA']._serialized_start=226
  _globals['_ISSUEDATA']._serialized_end=445
  _globals['_ISSUECOMPONENT']._serialized_start=448
  _globals['_ISSUECOMPONENT']._serialized_end=603
  _globals['_REQUIREMENTS']._serialized_start=606
  _globals['_REQUIREMENTS']._serialized_end=737
# @@protoc_insertion_point(module_scope)
