# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: planner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'planner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplanner.proto\x12\x0csdlc.planner\x1a\x0c\x63ommon.proto\"\x90\x01\n\rPlannerOutput\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.sdlc.common.Status\x12\x12\n\nconfidence\x18\x03 \x01(\x05\x12 \n\x04plan\x18\x04 \x01(\x0b\x32\x12.sdlc.planner.Plan\x12\x15\n\rmarkdown_body\x18\x05 \x01(\t\"\xb1\x01\n\x04Plan\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12!\n\x05tasks\x18\x03 \x03(\x0b\x32\x12.sdlc.planner.Task\x12\x31\n\x08strategy\x18\x04 \x01(\x0b\x32\x1f.sdlc.planner.ExecutionStrategy\x12\x33\n\x0c\x64\x65pendencies\x18\x05 \x01(\x0b\x32\x1d.sdlc.planner.DependencyGraph\"\x89\x02\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12)\n\x05\x66iles\x18\x04 \x03(\x0b\x32\x1a.sdlc.common.FileReference\x12\x12\n\ndepends_on\x18\x05 \x03(\t\x12\x0e\n\x06\x62locks\x18\x06 \x03(\t\x12\x10\n\x08\x61pproach\x18\x07 \x01(\t\x12\x15\n\x08playbook\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x61gent\x18\t \x01(\t\x12\x12\n\ncomplexity\x18\n \x01(\x05\x12\x16\n\x0e\x65stimated_time\x18\x0b \x01(\t\x12\x12\n\ntest_cases\x18\x0c \x03(\tB\x0b\n\t_playbook\"k\n\x11\x45xecutionStrategy\x12\x0c\n\x04type\x18\x01 \x01(\t\x12,\n\x06phases\x18\x02 \x03(\x0b\x32\x1c.sdlc.planner.ExecutionPhase\x12\x1a\n\x12max_parallel_tasks\x18\x03 \x01(\x05\"W\n\x0e\x45xecutionPhase\x12\r\n\x05order\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08task_ids\x18\x03 \x03(\t\x12\x16\n\x0e\x65xecution_mode\x18\x04 \x01(\t\"h\n\x0f\x44\x65pendencyGraph\x12+\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x1c.sdlc.planner.DependencyEdge\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\x12\x15\n\rcritical_path\x18\x03 \x03(\t\"J\n\x0e\x44\x65pendencyEdge\x12\x11\n\tfrom_task\x18\x01 \x01(\t\x12\x0f\n\x07to_task\x18\x02 \x01(\t\x12\x14\n\x0crelationship\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANNEROUTPUT']._serialized_start=46
  _globals['_PLANNEROUTPUT']._serialized_end=190
  _globals['_PLAN']._serialized_start=193
  _globals['_PLAN']._serialized_end=370
  _globals['_TASK']._serialized_start=373
  _globals['_TASK']._serialized_end=638
  _globals['_EXECUTIONSTRATEGY']._serialized_start=640
  _globals['_EXECUTIONSTRATEGY']._serialized_end=747
  _globals['_EXECUTIONPHASE']._serialized_start=749
  _globals['_EXECUTIONPHASE']._serialized_end=836
  _globals['_DEPENDENCYGRAPH']._serialized_start=838
  _globals['_DEPENDENCYGRAPH']._serialized_end=942
  _globals['_DEPENDENCYEDGE']._serialized_start=944
  _globals['_DEPENDENCYEDGE']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
